[2024-04-13T20:07:06.343-0400] {processor.py:161} INFO - Started process (PID=31672) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T20:07:06.343-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T20:07:06.343-0400] {logging_mixin.py:188} INFO - [2024-04-13T20:07:06.343-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T20:07:06.382-0400] {logging_mixin.py:188} INFO - [2024-04-13T20:07:06.382-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T20:07:06.382-0400] {logging_mixin.py:188} INFO - [2024-04-13T20:07:06.382-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T20:07:06.383-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T20:07:06.408-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-13T22:09:22.299-0400] {processor.py:161} INFO - Started process (PID=31883) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T22:09:22.299-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T22:09:22.300-0400] {logging_mixin.py:188} INFO - [2024-04-13T22:09:22.299-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T22:09:22.338-0400] {logging_mixin.py:188} INFO - [2024-04-13T22:09:22.338-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T22:09:22.338-0400] {logging_mixin.py:188} INFO - [2024-04-13T22:09:22.338-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T22:09:22.338-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T22:09:22.363-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T01:11:54.540-0400] {processor.py:161} INFO - Started process (PID=32090) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T01:11:54.541-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T01:11:54.541-0400] {logging_mixin.py:188} INFO - [2024-04-14T01:11:54.541-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T01:11:54.578-0400] {logging_mixin.py:188} INFO - [2024-04-14T01:11:54.578-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T01:11:54.578-0400] {logging_mixin.py:188} INFO - [2024-04-14T01:11:54.578-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T01:11:54.578-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T01:11:54.604-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-04-14T04:04:48.219-0400] {processor.py:161} INFO - Started process (PID=32358) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T04:04:48.220-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T04:04:48.220-0400] {logging_mixin.py:188} INFO - [2024-04-14T04:04:48.220-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T04:04:48.259-0400] {logging_mixin.py:188} INFO - [2024-04-14T04:04:48.259-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T04:04:48.259-0400] {logging_mixin.py:188} INFO - [2024-04-14T04:04:48.259-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T04:04:48.259-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T04:04:48.285-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T06:21:49.124-0400] {processor.py:161} INFO - Started process (PID=32545) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T06:21:49.125-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T06:21:49.126-0400] {logging_mixin.py:188} INFO - [2024-04-14T06:21:49.126-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T06:21:49.163-0400] {logging_mixin.py:188} INFO - [2024-04-14T06:21:49.163-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T06:21:49.163-0400] {logging_mixin.py:188} INFO - [2024-04-14T06:21:49.163-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T06:21:49.163-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T06:21:49.189-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T08:10:03.823-0400] {processor.py:161} INFO - Started process (PID=32726) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:10:03.824-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T08:10:03.824-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:10:03.824-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:10:03.865-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:10:03.864-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T08:10:03.865-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:10:03.865-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T08:10:03.865-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:10:03.891-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-04-14T08:15:01.684-0400] {processor.py:161} INFO - Started process (PID=32845) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:15:01.686-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T08:15:01.686-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:15:01.686-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:15:01.724-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:15:01.724-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T08:15:01.724-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:15:01.724-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T08:15:01.724-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:15:01.750-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T08:22:03.253-0400] {processor.py:161} INFO - Started process (PID=32966) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:22:03.254-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T08:22:03.255-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:22:03.254-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:22:03.292-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:22:03.292-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T08:22:03.292-0400] {logging_mixin.py:188} INFO - [2024-04-14T08:22:03.292-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T08:22:03.292-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T08:22:03.317-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T11:22:01.475-0400] {processor.py:161} INFO - Started process (PID=33136) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T11:22:01.477-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T11:22:01.477-0400] {logging_mixin.py:188} INFO - [2024-04-14T11:22:01.477-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T11:22:01.519-0400] {logging_mixin.py:188} INFO - [2024-04-14T11:22:01.519-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T11:22:01.519-0400] {logging_mixin.py:188} INFO - [2024-04-14T11:22:01.519-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T11:22:01.519-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T11:22:01.545-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-04-14T12:06:59.367-0400] {processor.py:161} INFO - Started process (PID=33265) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T12:06:59.367-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T12:06:59.367-0400] {logging_mixin.py:188} INFO - [2024-04-14T12:06:59.367-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T12:06:59.406-0400] {logging_mixin.py:188} INFO - [2024-04-14T12:06:59.406-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T12:06:59.407-0400] {logging_mixin.py:188} INFO - [2024-04-14T12:06:59.406-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T12:06:59.407-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T12:06:59.432-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T14:14:12.522-0400] {processor.py:161} INFO - Started process (PID=33472) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T14:14:12.523-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T14:14:12.523-0400] {logging_mixin.py:188} INFO - [2024-04-14T14:14:12.523-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T14:14:12.560-0400] {logging_mixin.py:188} INFO - [2024-04-14T14:14:12.560-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T14:14:12.560-0400] {logging_mixin.py:188} INFO - [2024-04-14T14:14:12.560-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T14:14:12.560-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T14:14:12.585-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-04-14T16:05:17.103-0400] {processor.py:161} INFO - Started process (PID=33633) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:05:17.104-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:05:17.104-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:05:17.104-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:05:17.141-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:05:17.141-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:05:17.142-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:05:17.141-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:05:17.142-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:05:17.167-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-04-14T16:37:03.848-0400] {processor.py:161} INFO - Started process (PID=33770) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:37:03.849-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:37:03.849-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:37:03.849-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:37:03.889-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:37:03.889-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:37:03.889-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:37:03.889-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:37:03.889-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:37:03.915-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T16:39:04.851-0400] {processor.py:161} INFO - Started process (PID=33864) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:39:04.851-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:39:04.852-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:39:04.852-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:39:04.890-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:39:04.889-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:39:04.890-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:39:04.890-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:39:04.890-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:39:04.915-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-04-14T16:41:01.189-0400] {processor.py:161} INFO - Started process (PID=33963) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:41:01.190-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:41:01.190-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:41:01.190-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:41:01.229-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:41:01.228-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:41:01.229-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:41:01.229-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:41:01.229-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:41:01.254-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T16:42:55.111-0400] {processor.py:161} INFO - Started process (PID=34063) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:42:55.113-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:42:55.113-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:42:55.113-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:42:55.151-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:42:55.151-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:42:55.152-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:42:55.152-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:42:55.152-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:42:55.177-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T16:44:57.028-0400] {processor.py:161} INFO - Started process (PID=34164) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:44:57.029-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:44:57.030-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:44:57.030-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:44:57.068-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:44:57.068-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:44:57.069-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:44:57.069-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:44:57.069-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:44:57.095-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-04-14T16:46:56.095-0400] {processor.py:161} INFO - Started process (PID=34275) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:46:56.096-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:46:56.096-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:46:56.096-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:46:56.134-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:46:56.134-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:46:56.134-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:46:56.134-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:46:56.134-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:46:56.160-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T16:48:52.423-0400] {processor.py:161} INFO - Started process (PID=34373) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:48:52.423-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:48:52.424-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:48:52.423-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:48:52.464-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:48:52.464-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:48:52.464-0400] {logging_mixin.py:188} INFO - [2024-04-14T16:48:52.464-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:48:52.464-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:48:52.490-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-04-14T17:15:51.849-0400] {processor.py:161} INFO - Started process (PID=34529) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:15:51.850-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:15:51.850-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:15:51.850-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:15:51.891-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:15:51.890-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:15:51.891-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:15:51.891-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:15:51.891-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:15:51.917-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-04-14T17:17:54.110-0400] {processor.py:161} INFO - Started process (PID=34790) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:17:54.111-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:17:54.111-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:17:54.111-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:17:54.152-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:17:54.152-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:17:54.152-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:17:54.152-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:17:54.152-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:17:54.178-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-04-14T17:19:48.373-0400] {processor.py:161} INFO - Started process (PID=34899) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:19:48.374-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:19:48.374-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:19:48.374-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:19:48.413-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:19:48.412-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:19:48.413-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:19:48.413-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:19:48.413-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:19:48.438-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T17:21:44.868-0400] {processor.py:161} INFO - Started process (PID=34994) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:21:44.869-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:21:44.869-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:21:44.869-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:21:44.907-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:21:44.907-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:21:44.907-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:21:44.907-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:21:44.907-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:21:44.933-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T17:23:37.265-0400] {processor.py:161} INFO - Started process (PID=35085) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:23:37.267-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:23:37.267-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:23:37.267-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:23:37.305-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:23:37.305-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:23:37.305-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:23:37.305-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:23:37.305-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:23:37.331-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:25:36.418-0400] {processor.py:161} INFO - Started process (PID=35184) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:25:36.419-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:25:36.419-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:25:36.419-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:25:36.458-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:25:36.458-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:25:36.458-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:25:36.458-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:25:36.458-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:25:36.484-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:27:33.373-0400] {processor.py:161} INFO - Started process (PID=35283) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:27:33.375-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:27:33.375-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:27:33.375-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:27:33.413-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:27:33.413-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:27:33.414-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:27:33.413-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:27:33.414-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:27:33.439-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:29:27.936-0400] {processor.py:161} INFO - Started process (PID=35393) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:29:27.937-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:29:27.937-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:29:27.937-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:29:27.976-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:29:27.975-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:29:27.976-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:29:27.976-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:29:27.976-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:29:28.001-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:31:25.680-0400] {processor.py:161} INFO - Started process (PID=35532) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:31:25.681-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:31:25.681-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:31:25.681-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:31:25.719-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:31:25.719-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:31:25.719-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:31:25.719-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:31:25.722-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:31:25.748-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-04-14T17:33:24.345-0400] {processor.py:161} INFO - Started process (PID=35639) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:33:24.346-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:33:24.346-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:33:24.346-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:33:24.385-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:33:24.385-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:33:24.386-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:33:24.385-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:33:24.386-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:33:24.411-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-04-14T17:35:27.918-0400] {processor.py:161} INFO - Started process (PID=35738) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:35:27.919-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:35:27.919-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:35:27.919-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:35:27.958-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:35:27.958-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:35:27.958-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:35:27.958-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:35:27.958-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:35:27.984-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:37:21.749-0400] {processor.py:161} INFO - Started process (PID=35833) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:37:21.751-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:37:21.751-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:37:21.751-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:37:21.789-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:37:21.788-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:37:21.789-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:37:21.789-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:37:21.789-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:37:21.814-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T17:39:11.841-0400] {processor.py:161} INFO - Started process (PID=35922) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:39:11.841-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:39:11.842-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:39:11.841-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:39:11.880-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:39:11.880-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:39:11.880-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:39:11.880-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:39:11.880-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:39:11.905-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T17:41:04.098-0400] {processor.py:161} INFO - Started process (PID=36010) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:41:04.099-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:41:04.099-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:41:04.099-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:41:04.138-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:41:04.138-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:41:04.138-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:41:04.138-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:41:04.138-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:41:04.164-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:42:54.981-0400] {processor.py:161} INFO - Started process (PID=36096) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:42:54.982-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:42:54.982-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:42:54.982-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:42:55.021-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:42:55.021-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:42:55.021-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:42:55.021-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:42:55.021-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:42:55.047-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:44:50.561-0400] {processor.py:161} INFO - Started process (PID=36184) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:44:50.562-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:44:50.562-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:44:50.562-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:44:50.600-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:44:50.600-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:44:50.601-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:44:50.600-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:44:50.601-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:44:50.626-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T17:46:54.021-0400] {processor.py:161} INFO - Started process (PID=36277) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:46:54.022-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:46:54.023-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:46:54.023-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:46:54.060-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:46:54.060-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:46:54.061-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:46:54.061-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:46:54.061-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:46:54.086-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T17:48:54.282-0400] {processor.py:161} INFO - Started process (PID=36369) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:48:54.284-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:48:54.284-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:48:54.284-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:48:54.322-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:48:54.322-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:48:54.322-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:48:54.322-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:48:54.322-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:48:54.348-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:50:49.689-0400] {processor.py:161} INFO - Started process (PID=36472) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:50:49.690-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:50:49.690-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:50:49.690-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:50:49.728-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:50:49.727-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:50:49.728-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:50:49.728-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:50:49.728-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:50:49.753-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-04-14T17:52:45.181-0400] {processor.py:161} INFO - Started process (PID=36554) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:52:45.182-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:52:45.182-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:52:45.182-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:52:45.220-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:52:45.220-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:52:45.220-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:52:45.220-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:52:45.220-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:52:45.246-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T17:54:41.414-0400] {processor.py:161} INFO - Started process (PID=36642) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:54:41.415-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:54:41.415-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:54:41.415-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:54:41.455-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:54:41.455-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:54:41.455-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:54:41.455-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:54:41.455-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:54:41.481-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-04-14T17:56:33.082-0400] {processor.py:161} INFO - Started process (PID=36788) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:56:33.083-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:56:33.083-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:56:33.083-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:56:33.121-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:56:33.121-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:56:33.121-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:56:33.121-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:56:33.121-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:56:33.147-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T17:58:32.096-0400] {processor.py:161} INFO - Started process (PID=36885) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:58:32.097-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T17:58:32.097-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:58:32.097-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:58:32.136-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:58:32.136-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T17:58:32.136-0400] {logging_mixin.py:188} INFO - [2024-04-14T17:58:32.136-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T17:58:32.136-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T17:58:32.162-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T18:00:25.437-0400] {processor.py:161} INFO - Started process (PID=36987) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:00:25.438-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:00:25.438-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:00:25.438-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:00:25.478-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:00:25.478-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:00:25.478-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:00:25.478-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:00:25.478-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:00:25.505-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-04-14T18:02:28.946-0400] {processor.py:161} INFO - Started process (PID=37088) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:02:28.948-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:02:28.948-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:02:28.948-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:02:28.988-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:02:28.988-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:02:28.988-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:02:28.988-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:02:28.988-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:02:29.014-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-04-14T18:04:25.198-0400] {processor.py:161} INFO - Started process (PID=37179) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:04:25.199-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:04:25.200-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:04:25.200-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:04:25.238-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:04:25.238-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:04:25.239-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:04:25.238-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:04:25.239-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:04:25.264-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T18:06:22.968-0400] {processor.py:161} INFO - Started process (PID=37275) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:06:22.969-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:06:22.969-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:06:22.969-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:06:23.009-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:06:23.009-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:06:23.009-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:06:23.009-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:06:23.009-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:06:23.035-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-04-14T18:08:22.710-0400] {processor.py:161} INFO - Started process (PID=37380) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:08:22.710-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:08:22.711-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:08:22.711-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:08:22.756-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:08:22.755-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:08:22.756-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:08:22.756-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:08:22.756-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:08:22.782-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2024-04-14T18:10:14.012-0400] {processor.py:161} INFO - Started process (PID=37479) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:10:14.013-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:10:14.013-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:10:14.013-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:10:14.052-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:10:14.052-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:10:14.052-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:10:14.052-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:10:14.052-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:10:14.077-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-14T18:12:10.591-0400] {processor.py:161} INFO - Started process (PID=37591) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:12:10.593-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:12:10.593-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:12:10.593-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:12:10.631-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:12:10.631-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:12:10.632-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:12:10.632-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:12:10.632-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:12:10.657-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-14T18:14:11.406-0400] {processor.py:161} INFO - Started process (PID=37690) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:14:11.406-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:14:11.407-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:14:11.407-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:14:11.445-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:14:11.445-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:14:11.446-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:14:11.445-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:14:11.446-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:14:11.473-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-04-14T18:16:08.527-0400] {processor.py:161} INFO - Started process (PID=37792) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:16:08.529-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T18:16:08.529-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:16:08.529-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:16:08.567-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:16:08.567-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T18:16:08.567-0400] {logging_mixin.py:188} INFO - [2024-04-14T18:16:08.567-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T18:16:08.567-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T18:16:08.593-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
